# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e77ba15ee816bcc30c9a2e20a44f9400f2e7b37c62a067ed54fc23c847e60cf394426dbadaf09ddb15a63d090ac325dd1d59678785550e602347f35028f0c56

test:
  secret_key_base: 8bdcef81aa306f15c7a86c800e60b100580de0ea36d565d8d04970c4a036290e5137fba6bfd6f05df6b5e482c13bcd4e09d51046c3504d078e5d6367987cc939

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
